# Generated by Django 4.1.7 on 2023-07-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extensions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='first_name',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='age',
            new_name='Extension',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='last_name',
            new_name='Section',
        ),
    ]
